services:
  fastapi-app:
    container_name: API
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8000"  # 호스트의 8002번 포트를 컨테이너의 8000번 포트에 매핑
    environment:
      - PYTHONUNBUFFERED=1
    restart: always  # 컨테이너가 실패 시 자동으로 재시작
    networks:
      - custom_network  # custom_network 사용

networks:
  custom_network:
    external: true  # 이미 생성된 외부 네트워크를 사용
